---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: cert-manager-operator
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: openshift-cert-manager-operator/operator/overlays/stable-v1
    repoURL: >-
      https://github.com/tim-stasse/gitops-catalog
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
