---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crunchydata-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: openshift-operators
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: 3-operators/crunchydata/overlays/v5
    repoURL: >-
      https://github.com/tim-stasse/silent-auction-demo-infra.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
