---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhbk-instance
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: openshift-operators
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: 3-operators/rhbk-instance/overlays/default
    repoURL: >-
      https://github.com/tim-stasse/silent-auction-demo-infra.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
