---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhcl-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: kuadrant-system
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: redhat-connectivity-link/operator/overlays/stable
    repoURL: >-
      https://github.com/tim-stasse/gitops-catalog
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
