---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-management
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 3-operators/secrets
    repoURL: >-
      git@github.com:tim-stasse/silent-auction-demo-infra.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
