---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-connect
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: vault
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - chart: connect
      repoURL: https://1password.github.io/connect-helm-charts
      targetRevision: 1.15.1
      helm:
        releaseName: connect
        valueFiles:
          - $values/3-operators/secrets/1password-connect-instance-values.yaml
    - repoURL: https://github.com/tim-stasse/silent-auction-demo-infra.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
